package com.palle;

import java.util.List;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
@RequestMapping
public class SpringBootCusManageCrudApplication {
private final CustomerRepository customerRepository ;
    
    public SpringBootCusManageCrudApplication(CustomerRepository customerRepository)
    {
       this.customerRepository=customerRepository;	
    }    
    

	public static void main(String[] args) {
		SpringApplication.run(SpringBootCusManageCrudApplication.class, args);
	}
	
	//adding new cus in post we create obj here
	record NewCustomerRequest(Integer id,String name,String email,Integer age) {}
	
	@GetMapping("/welcome")
	public List<Customer> customerShowList()
	{
	   return customerRepository.findAll();
	}
	
	//call that obj in postmethod
	@PostMapping("/add")
	public void addCustomer( @RequestBody NewCustomerRequest newCustomerRequest)
	{
		Customer customer=new Customer();
		//id autogenerated so default
		customer.setId(newCustomerRequest.id);
		customer.setName(newCustomerRequest.name);
		customer.setEmail(newCustomerRequest.email);
		customer.setAge(newCustomerRequest.age);
		
		customerRepository.save(customer);
		
	}
	
	@DeleteMapping("{customerid}")
	public void deleteCustomer(@PathVariable("customerid") Integer Id)
	{
		customerRepository.deleteById(Id);
		
	}
	
	/*@PutMapping("/upd")  
	private void update(@RequestBody Customer customer)  
	
	{  
		customerRepository.saveOrUpdate(customer);  
	 
	} */
	
	
	
	
}
